-- Flyway migration: Initial schema for reconciliation
-- Extracted from schema.sql (excluding backup and *_DDMMYY/_YYMMDD objects and audit_* tables outside the audit schema).

CREATE SCHEMA reconciliation;

CREATE TABLE reconciliation.bank_account (
    id bigint NOT NULL,
    account_no character varying(64) NOT NULL,
    iban character varying(34),
    currency character(3) NOT NULL,
    bank_bic character varying(11),
    holder_name character varying(128),
    is_active boolean DEFAULT true NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    employer_id character varying(64) DEFAULT NULL::character varying
);

ALTER TABLE ONLY reconciliation.bank_account FORCE ROW LEVEL SECURITY;

ALTER TABLE reconciliation.bank_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.bank_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.entity_audit_event (
    id bigint NOT NULL,
    occurred_at timestamp without time zone NOT NULL,
    audit_number character varying(64) NOT NULL,
    record_number character varying(128) NOT NULL,
    entity_type character varying(128) NOT NULL,
    entity_id character varying(128),
    operation character varying(64) NOT NULL,
    performed_by character varying(128),
    trace_id character varying(64),
    metadata jsonb,
    old_values jsonb,
    new_values jsonb,
    change_summary text,
    client_ip character varying(45),
    user_agent character varying(512),
    prev_hash character(64) NOT NULL,
    hash character(64) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE reconciliation.entity_audit_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.entity_audit_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.file_processing_queue (
    id bigint NOT NULL,
    file_id character varying(100) NOT NULL,
    uploaded_file_id bigint,
    processing_status text DEFAULT 'PENDING'::text,
    priority integer DEFAULT 5,
    retry_count integer DEFAULT 0,
    max_retries integer DEFAULT 3,
    error_message text,
    processing_started_at timestamp without time zone,
    processing_completed_at timestamp without time zone,
    processed_by character varying(64),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    employer_id character varying(64) DEFAULT NULL::character varying,
    CONSTRAINT file_processing_queue_processing_status_enum_check CHECK ((processing_status = ANY (ARRAY['PENDING'::text, 'IN_PROGRESS'::text, 'COMPLETED'::text, 'FAILED'::text, 'CANCELLED'::text])))
);

ALTER TABLE ONLY reconciliation.file_processing_queue FORCE ROW LEVEL SECURITY;

ALTER TABLE reconciliation.file_processing_queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.file_processing_queue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.import_error (
    id bigint NOT NULL,
    import_run_id bigint NOT NULL,
    statement_file_id bigint,
    line_no integer,
    code character varying(64) NOT NULL,
    message text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    employer_id character varying(64) DEFAULT NULL::character varying
);

ALTER TABLE ONLY reconciliation.import_error FORCE ROW LEVEL SECURITY;

ALTER TABLE reconciliation.import_error ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.import_error_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.import_run (
    id bigint NOT NULL,
    filename character varying(255) NOT NULL,
    file_hash character(64) NOT NULL,
    file_size_bytes bigint NOT NULL,
    received_at timestamp without time zone NOT NULL,
    status text NOT NULL,
    error_message text,
    board_id character varying(64) DEFAULT NULL::character varying,
    employer_id character varying(64) DEFAULT NULL::character varying,
    CONSTRAINT import_run_status_enum_check CHECK ((status = ANY (ARRAY['NEW'::text, 'PARSED'::text, 'PARTIAL'::text, 'FAILED'::text, 'IMPORTED'::text, 'DUPLICATE'::text])))
);

ALTER TABLE ONLY reconciliation.import_run FORCE ROW LEVEL SECURITY;

ALTER TABLE reconciliation.import_run ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.import_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.raw_statement_line (
    id bigint NOT NULL,
    statement_file_id bigint NOT NULL,
    line_no integer NOT NULL,
    tag character varying(8),
    raw_text text NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    employer_id character varying(64) DEFAULT NULL::character varying
);

ALTER TABLE ONLY reconciliation.raw_statement_line FORCE ROW LEVEL SECURITY;

ALTER TABLE reconciliation.raw_statement_line ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.raw_statement_line_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.statement_balance (
    id bigint NOT NULL,
    statement_file_id bigint NOT NULL,
    bal_type text NOT NULL,
    dc text NOT NULL,
    bal_date date NOT NULL,
    currency character(3) NOT NULL,
    amount numeric(19,2) NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    employer_id character varying(64) DEFAULT NULL::character varying,
    CONSTRAINT statement_balance_bal_type_enum_check CHECK ((bal_type = ANY (ARRAY['OPENING'::text, 'CLOSING'::text, 'AVAILABLE'::text, 'FORWARD'::text]))),
    CONSTRAINT statement_balance_dc_enum_check CHECK ((dc = ANY (ARRAY['D'::text, 'C'::text])))
);

ALTER TABLE ONLY reconciliation.statement_balance FORCE ROW LEVEL SECURITY;

ALTER TABLE reconciliation.statement_balance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.statement_balance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.statement_file (
    id bigint NOT NULL,
    import_run_id bigint NOT NULL,
    bank_account_id bigint NOT NULL,
    stmt_ref_20 character varying(35) NOT NULL,
    seq_28c character varying(35),
    statement_date date NOT NULL,
    opening_dc text NOT NULL,
    opening_amount numeric(19,2) NOT NULL,
    closing_dc text NOT NULL,
    closing_amount numeric(19,2) NOT NULL,
    currency character(3) NOT NULL,
    is_interim boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    employer_id character varying(64) DEFAULT NULL::character varying,
    CONSTRAINT statement_file_closing_dc_enum_check CHECK ((closing_dc = ANY (ARRAY['D'::text, 'C'::text]))),
    CONSTRAINT statement_file_opening_dc_enum_check CHECK ((opening_dc = ANY (ARRAY['D'::text, 'C'::text])))
);

ALTER TABLE ONLY reconciliation.statement_file FORCE ROW LEVEL SECURITY;

ALTER TABLE reconciliation.statement_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.statement_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.statement_transaction (
    id bigint NOT NULL,
    statement_file_id bigint NOT NULL,
    line_no integer NOT NULL,
    value_date date NOT NULL,
    entry_date date,
    dc text NOT NULL,
    amount numeric(19,2) NOT NULL,
    signed_amount numeric(19,2) NOT NULL,
    currency character(3) NOT NULL,
    txn_type_code character varying(4),
    bank_reference character varying(35),
    customer_reference character varying(35),
    entry_reference character varying(16),
    narrative text,
    narrative_tokens jsonb,
    ext_idempotency_hash character(64) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    employer_id character varying(64) DEFAULT NULL::character varying,
    CONSTRAINT statement_transaction_dc_enum_check CHECK ((dc = ANY (ARRAY['D'::text, 'C'::text])))
);

ALTER TABLE ONLY reconciliation.statement_transaction FORCE ROW LEVEL SECURITY;

ALTER TABLE reconciliation.statement_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.statement_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.transaction_86_segment (
    id bigint NOT NULL,
    statement_transaction_id bigint NOT NULL,
    seg_key character varying(32) NOT NULL,
    seg_value character varying(512),
    seg_seq integer NOT NULL
);

ALTER TABLE reconciliation.transaction_86_segment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.transaction_86_segment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.uploaded_files (
    id bigint NOT NULL,
    filename character varying(255) NOT NULL,
    stored_path character varying(500) NOT NULL,
    file_hash character varying(64) NOT NULL,
    file_type character varying(50) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    uploaded_by character varying(100),
    total_records integer DEFAULT 0 NOT NULL,
    success_count integer DEFAULT 0 NOT NULL,
    failure_count integer DEFAULT 0 NOT NULL,
    status character varying(50) NOT NULL,
    file_reference_number character varying(100)
);

ALTER TABLE reconciliation.uploaded_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.uploaded_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.van_file (
    id bigint NOT NULL,
    import_run_id bigint NOT NULL,
    file_generation_date_time timestamp without time zone,
    file_sequence_number character varying(255),
    batch_id character varying(255),
    currency_code character(3),
    created_at timestamp without time zone NOT NULL
);

ALTER TABLE reconciliation.van_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.van_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reconciliation.van_transaction (
    id bigint NOT NULL,
    import_run_id bigint NOT NULL,
    main_account_number character varying(255) NOT NULL,
    virtual_account_number character varying(255) NOT NULL,
    transaction_reference_number character varying(255),
    bank_reference_trace_id character varying(255),
    remitter_name character varying(255),
    remitter_account_number character varying(255),
    remitter_ifsc_bank_name character varying(255),
    remitter_vpa character varying(255),
    transaction_date date NOT NULL,
    value_date date,
    amount numeric(19,2) NOT NULL,
    mode_channel character varying(255),
    payment_description_narration character varying(255),
    payment_status character varying(255),
    mapped_customer_id_code character varying(255),
    invoice_reference_id character varying(255),
    date_time_of_credit timestamp without time zone,
    branch_bank_code character varying(255),
    created_at timestamp without time zone NOT NULL
);

ALTER TABLE reconciliation.van_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reconciliation.van_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY reconciliation.bank_account
    ADD CONSTRAINT bank_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.bank_account
    ADD CONSTRAINT bank_account_uq_account UNIQUE (account_no, currency);

ALTER TABLE ONLY reconciliation.entity_audit_event
    ADD CONSTRAINT entity_audit_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.entity_audit_event
    ADD CONSTRAINT entity_audit_event_uq_entity_audit_event_audit_number UNIQUE (audit_number);

ALTER TABLE ONLY reconciliation.file_processing_queue
    ADD CONSTRAINT file_processing_queue_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.import_error
    ADD CONSTRAINT import_error_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.import_run
    ADD CONSTRAINT import_run_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.import_run
    ADD CONSTRAINT import_run_uq_filehash UNIQUE (file_hash);

ALTER TABLE ONLY reconciliation.raw_statement_line
    ADD CONSTRAINT raw_statement_line_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.statement_balance
    ADD CONSTRAINT statement_balance_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.statement_file
    ADD CONSTRAINT statement_file_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.statement_file
    ADD CONSTRAINT statement_file_uq_stmt UNIQUE (bank_account_id, stmt_ref_20, seq_28c);

ALTER TABLE ONLY reconciliation.statement_transaction
    ADD CONSTRAINT statement_transaction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.statement_transaction
    ADD CONSTRAINT statement_transaction_uq_txn_hash UNIQUE (ext_idempotency_hash);

ALTER TABLE ONLY reconciliation.transaction_86_segment
    ADD CONSTRAINT transaction_86_segment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.uploaded_files
    ADD CONSTRAINT uploaded_files_file_reference_number UNIQUE (file_reference_number);

ALTER TABLE ONLY reconciliation.uploaded_files
    ADD CONSTRAINT uploaded_files_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.van_file
    ADD CONSTRAINT van_file_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reconciliation.van_transaction
    ADD CONSTRAINT van_transaction_pkey PRIMARY KEY (id);

CREATE INDEX idx_bank_account_board_employer ON reconciliation.bank_account USING btree (board_id, employer_id);

CREATE INDEX idx_file_processing_queue_board_employer ON reconciliation.file_processing_queue USING btree (board_id, employer_id);

CREATE INDEX idx_import_error_board_employer ON reconciliation.import_error USING btree (board_id, employer_id);

CREATE INDEX idx_import_run_board_employer ON reconciliation.import_run USING btree (board_id, employer_id);

CREATE INDEX idx_raw_statement_line_board_employer ON reconciliation.raw_statement_line USING btree (board_id, employer_id);

CREATE INDEX idx_statement_balance_board_employer ON reconciliation.statement_balance USING btree (board_id, employer_id);

CREATE INDEX idx_statement_file_board_employer ON reconciliation.statement_file USING btree (board_id, employer_id);

CREATE INDEX idx_statement_transaction_board_employer ON reconciliation.statement_transaction USING btree (board_id, employer_id);

ALTER TABLE ONLY reconciliation.van_file
    ADD CONSTRAINT van_file_fk_van_file_import_run FOREIGN KEY (import_run_id) REFERENCES reconciliation.import_run(id);

ALTER TABLE ONLY reconciliation.van_transaction
    ADD CONSTRAINT van_transaction_fk_van_transaction_import_run FOREIGN KEY (import_run_id) REFERENCES reconciliation.import_run(id);

ALTER TABLE reconciliation.bank_account ENABLE ROW LEVEL SECURITY;

CREATE POLICY bank_account_std_read ON reconciliation.bank_account FOR SELECT USING (auth.can_read_row(board_id, employer_id));

CREATE POLICY bank_account_std_write ON reconciliation.bank_account USING (auth.can_write_row(board_id, employer_id)) WITH CHECK (auth.can_write_row(board_id, employer_id));

ALTER TABLE reconciliation.file_processing_queue ENABLE ROW LEVEL SECURITY;

CREATE POLICY file_processing_queue_std_read ON reconciliation.file_processing_queue FOR SELECT USING (auth.can_read_row(board_id, employer_id));

CREATE POLICY file_processing_queue_std_write ON reconciliation.file_processing_queue USING (auth.can_write_row(board_id, employer_id)) WITH CHECK (auth.can_write_row(board_id, employer_id));

ALTER TABLE reconciliation.import_error ENABLE ROW LEVEL SECURITY;

CREATE POLICY import_error_std_read ON reconciliation.import_error FOR SELECT USING (auth.can_read_row(board_id, employer_id));

CREATE POLICY import_error_std_write ON reconciliation.import_error USING (auth.can_write_row(board_id, employer_id)) WITH CHECK (auth.can_write_row(board_id, employer_id));

ALTER TABLE reconciliation.import_run ENABLE ROW LEVEL SECURITY;

CREATE POLICY import_run_std_read ON reconciliation.import_run FOR SELECT USING (auth.can_read_row(board_id, employer_id));

CREATE POLICY import_run_std_write ON reconciliation.import_run USING (auth.can_write_row(board_id, employer_id)) WITH CHECK (auth.can_write_row(board_id, employer_id));

ALTER TABLE reconciliation.raw_statement_line ENABLE ROW LEVEL SECURITY;

CREATE POLICY raw_statement_line_std_read ON reconciliation.raw_statement_line FOR SELECT USING (auth.can_read_row(board_id, employer_id));

CREATE POLICY raw_statement_line_std_write ON reconciliation.raw_statement_line USING (auth.can_write_row(board_id, employer_id)) WITH CHECK (auth.can_write_row(board_id, employer_id));

ALTER TABLE reconciliation.statement_balance ENABLE ROW LEVEL SECURITY;

CREATE POLICY statement_balance_std_read ON reconciliation.statement_balance FOR SELECT USING (auth.can_read_row(board_id, employer_id));

CREATE POLICY statement_balance_std_write ON reconciliation.statement_balance USING (auth.can_write_row(board_id, employer_id)) WITH CHECK (auth.can_write_row(board_id, employer_id));

ALTER TABLE reconciliation.statement_file ENABLE ROW LEVEL SECURITY;

CREATE POLICY statement_file_std_read ON reconciliation.statement_file FOR SELECT USING (auth.can_read_row(board_id, employer_id));

CREATE POLICY statement_file_std_write ON reconciliation.statement_file USING (auth.can_write_row(board_id, employer_id)) WITH CHECK (auth.can_write_row(board_id, employer_id));

ALTER TABLE reconciliation.statement_transaction ENABLE ROW LEVEL SECURITY;

CREATE POLICY statement_transaction_std_read ON reconciliation.statement_transaction FOR SELECT USING (auth.can_read_row(board_id, employer_id));

CREATE POLICY statement_transaction_std_write ON reconciliation.statement_transaction USING (auth.can_write_row(board_id, employer_id)) WITH CHECK (auth.can_write_row(board_id, employer_id));


--
-- PostgreSQL database dump complete
--

\unrestrict KhupiCfjLeP2xhdJ0I3VscKsJaEQ6HaoFKqi9vfSo5egFf5tVA6WVWc1WgjQPio
