-- Flyway migration: Initial schema for payment_flow
-- Extracted from schema.sql (excluding backup and *_DDMMYY/_YYMMDD objects and audit_* tables outside the audit schema).

CREATE SCHEMA IF NOT EXISTS payment_flow;

CREATE TABLE payment_flow.board_master (
    id bigint NOT NULL,
    board_id bigint NOT NULL,
    board_name character varying(200) NOT NULL,
    board_code character varying(20) NOT NULL,
    state_name character varying(100) NOT NULL,
    district_name character varying(100),
    address text,
    contact_person character varying(100),
    contact_email character varying(100),
    contact_phone character varying(20),
    status character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE ONLY payment_flow.board_master FORCE ROW LEVEL SECURITY;


ALTER TABLE payment_flow.board_master ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_flow.board_master_id_seq
);
ALTER SEQUENCE payment_flow.board_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE payment_flow.board_receipts (
    id bigint NOT NULL,
    board_id bigint NOT NULL,
    board_reference character varying(64) NOT NULL,
    employer_reference character varying(64) NOT NULL,
    employer_id bigint NOT NULL,
    toli_id bigint
);


ALTER TABLE payment_flow.board_receipts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_flow.board_receipts_id_seq
);
ALTER SEQUENCE payment_flow.board_receipts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE payment_flow.employer_master (
    id bigint NOT NULL,
    registration_number character varying(64) NOT NULL,
    establishment_name character varying(200) NOT NULL,
    address character varying(255),
    employer_name character varying(120),
    mobile_number character varying(15),
    email_id character varying(150),
    aadhar_number character(12),
    pan_number character varying(16),
    tan_number character varying(10),
    virtual_bank_account_number character varying(64),
    status character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    board_id bigint NOT NULL,
    aadhaar_number character varying(12),
    owner_name character varying(120),
    serial_no character varying(64)
    ,parent_employer_id bigint
    ,is_registered boolean DEFAULT false NOT NULL
);

COMMENT ON TABLE payment_flow.employer_master IS 'Stores establishment, contact, and compliance details for employers.';

CREATE SEQUENCE payment_flow.employer_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE payment_flow.employer_master_id_seq OWNED BY payment_flow.employer_master.id;

CREATE TABLE payment_flow.employer_payment_receipts (
    id bigint NOT NULL,
    employer_receipt_number character varying(40) NOT NULL,
    worker_receipt_number character varying(40) NOT NULL,
    employer_id bigint NOT NULL,
    toli_id bigint NOT NULL,
    transaction_reference character varying(50) NOT NULL,
    validated_by character varying(64) NOT NULL,
    validated_at timestamp without time zone NOT NULL,
    total_records integer NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    status character varying(32) NOT NULL,
    board_id bigint DEFAULT NULL
);

ALTER TABLE ONLY payment_flow.employer_payment_receipts FORCE ROW LEVEL SECURITY;


ALTER TABLE payment_flow.employer_payment_receipts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_flow.employer_payment_receipts_id_seq
);
ALTER SEQUENCE payment_flow.employer_payment_receipts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE payment_flow.employer_toli_relation (
    id bigint NOT NULL,
    employer_id bigint NOT NULL,
    toli_id bigint NOT NULL,
    toli_name character varying(120) NOT NULL,
    toli_code character varying(20),
    location character varying(200),
    supervisor_name character varying(100),
    supervisor_contact character varying(15),
    status character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    board_id bigint DEFAULT NULL
);

ALTER TABLE ONLY payment_flow.employer_toli_relation FORCE ROW LEVEL SECURITY;


ALTER TABLE payment_flow.employer_toli_relation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_flow.employer_toli_relation_id_seq
);
ALTER SEQUENCE payment_flow.employer_toli_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


CREATE TABLE payment_flow.worker_toli_relation (
    id bigint NOT NULL,
    worker_id bigint NOT NULL,
    toli_id bigint NOT NULL,
    board_id character varying(64) NOT NULL,
    employer_id character varying(64) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE payment_flow.worker_toli_relation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE payment_flow.worker_toli_relation_id_seq OWNED BY payment_flow.worker_toli_relation.id;

CREATE TABLE payment_flow.toli_master (
    id bigint NOT NULL,
    registration_number character varying(64) NOT NULL,
    employer_name_marathi character varying(200) NOT NULL,
    address character varying(255),
    employer_name_english character varying(200),
    mobile_number character varying(15),
    email_id character varying(150),
    status character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    board_id bigint NOT NULL,
    employer_id bigint NOT NULL,
    toli_id bigint NOT NULL
);

COMMENT ON TABLE payment_flow.toli_master IS 'Captures employer (toli) level details for registration and communication.';

CREATE SEQUENCE payment_flow.toli_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE payment_flow.toli_master_id_seq OWNED BY payment_flow.toli_master.id;

CREATE TABLE payment_flow.uploaded_files (
    id bigint NOT NULL,
    filename character varying(255) NOT NULL,
    stored_path character varying(500) NOT NULL,
    file_hash character varying(64) NOT NULL,
    file_type character varying(50) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    uploaded_by character varying(100),
    total_records integer DEFAULT 0 NOT NULL,
    success_count integer DEFAULT 0 NOT NULL,
    failure_count integer DEFAULT 0 NOT NULL,
    status character varying(50) NOT NULL,
    file_reference_number character varying(100),
    board_id bigint DEFAULT NULL,
    employer_id bigint DEFAULT NULL,
    toli_id bigint DEFAULT NULL
);

ALTER TABLE ONLY payment_flow.uploaded_files FORCE ROW LEVEL SECURITY;


ALTER TABLE payment_flow.uploaded_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_flow.uploaded_files_id_seq
);
ALTER SEQUENCE payment_flow.uploaded_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE payment_flow.worker_master (
    id bigint NOT NULL,
    worker_name_marathi character varying(120) NOT NULL,
    worker_name_english character varying(120),
    witness_name_1 character varying(120),
    witness_name_2 character varying(120),
    toli_number character varying(64),
    registration_number character varying(64) NOT NULL,
    pan_number character varying(16),
    nationality character varying(100),
    mother_name character varying(120),
    mobile_number character varying(15),
    mobile_number_1 character varying(15),
    marital_status character varying(30),
    ifsc_code character varying(11),
    branch_address character varying(255),
    bank_name character varying(120),
    age integer,
    address1 character varying(255),
    address2 character varying(255),
    account_number character varying(64),
    aadhar_number character(12) NOT NULL,
    status character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    board_id bigint NOT NULL
);

COMMENT ON TABLE payment_flow.worker_master IS 'Holds demographic and banking details for registered workers.';

CREATE SEQUENCE payment_flow.worker_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE payment_flow.worker_master_id_seq OWNED BY payment_flow.worker_master.id;

CREATE TABLE payment_flow.worker_payment_receipts (
    id bigint NOT NULL,
    receipt_number character varying(40) NOT NULL,
    employer_id character varying(64) NOT NULL,
    toli_id character varying(64) NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    created_at timestamp without time zone NOT NULL,
    total_records integer NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    status character varying(32) NOT NULL
);

ALTER TABLE ONLY payment_flow.worker_payment_receipts FORCE ROW LEVEL SECURITY;


ALTER TABLE payment_flow.worker_payment_receipts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_flow.worker_payment_receipts_id_seq
);
ALTER SEQUENCE payment_flow.worker_payment_receipts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE payment_flow.worker_payments (
    id bigint NOT NULL,
    worker_reference character varying(64) NOT NULL,
    registration_id character varying(64) NOT NULL,
    worker_name character varying(120) NOT NULL,
    employer_id character varying(64) NOT NULL,
    toli_id character varying(64) NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    toli character varying(64) NOT NULL,
    aadhar character varying(16) NOT NULL,
    pan character varying(16) NOT NULL,
    bank_account character varying(34) NOT NULL,
    payment_amount numeric(15,2) NOT NULL,
    file_id character varying(20),
    uploaded_file_ref character varying(100),
    request_reference_number character varying(40) NOT NULL,
    status character varying(40) DEFAULT 'UPLOADED'::character varying NOT NULL,
    receipt_number character varying(40),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE ONLY payment_flow.worker_payments FORCE ROW LEVEL SECURITY;


ALTER TABLE payment_flow.worker_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_flow.worker_payments_id_seq
);
ALTER SEQUENCE payment_flow.worker_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE payment_flow.worker_uploaded_data (
    id bigint NOT NULL,
    file_id character varying(100) NOT NULL,
    row_num integer NOT NULL,
    worker_id character varying(50),
    worker_name character varying(100),
    employer_id character varying(64) NOT NULL,
    toli_id character varying(64) NOT NULL,
    board_id character varying(64) DEFAULT NULL::character varying,
    company_name character varying(100),
    department character varying(50),
    "position" character varying(50),
    work_date date,
    hours_worked numeric(5,2),
    hourly_rate numeric(10,2),
    payment_amount numeric(15,2),
    bank_account character varying(20),
    phone_number character varying(15),
    email character varying(100),
    address text,
    status character varying(32) NOT NULL,
    rejection_reason text,
    created_at timestamp without time zone NOT NULL,
    validated_at timestamp without time zone,
    processed_at timestamp without time zone,
    receipt_number character varying(40),
    board_id bigint DEFAULT NULL,
    employer_id bigint DEFAULT NULL,
    toli_id bigint DEFAULT NULL
);

ALTER TABLE ONLY payment_flow.worker_uploaded_data FORCE ROW LEVEL SECURITY;


ALTER TABLE payment_flow.worker_uploaded_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_flow.worker_uploaded_data_id_seq
);
ALTER SEQUENCE payment_flow.worker_uploaded_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE ONLY payment_flow.employer_master ALTER COLUMN id SET DEFAULT nextval('payment_flow.employer_master_id_seq'::regclass);

ALTER TABLE ONLY payment_flow.worker_toli_relation ALTER COLUMN id SET DEFAULT nextval('payment_flow.worker_toli_relation_id_seq'::regclass);

ALTER TABLE ONLY payment_flow.toli_master ALTER COLUMN id SET DEFAULT nextval('payment_flow.toli_master_id_seq'::regclass);

ALTER TABLE ONLY payment_flow.worker_master ALTER COLUMN id SET DEFAULT nextval('payment_flow.worker_master_id_seq'::regclass);

ALTER TABLE ONLY payment_flow.board_master
    ADD CONSTRAINT board_master_board_code UNIQUE (board_code);

ALTER TABLE ONLY payment_flow.board_master
    ADD CONSTRAINT board_master_board_id UNIQUE (board_id);

ALTER TABLE ONLY payment_flow.board_master
    ADD CONSTRAINT board_master_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.board_receipts
    ADD CONSTRAINT board_receipts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.employer_master
    ADD CONSTRAINT employer_master_aadhaar_number_key UNIQUE (aadhaar_number);

ALTER TABLE ONLY payment_flow.employer_master
    ADD CONSTRAINT employer_master_aadhar_number UNIQUE (aadhar_number);

ALTER TABLE ONLY payment_flow.employer_master
    ADD CONSTRAINT employer_master_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.employer_master
    ADD CONSTRAINT employer_master_registration_number UNIQUE (registration_number);

ALTER TABLE ONLY payment_flow.employer_master
    ADD CONSTRAINT employer_master_serial_no_key UNIQUE (serial_no);

ALTER TABLE ONLY payment_flow.employer_master
    ADD CONSTRAINT employer_master_virtual_bank_account UNIQUE (virtual_bank_account_number);

-- Add self-referencing FK for parent_employer_id
ALTER TABLE ONLY payment_flow.employer_master
    ADD CONSTRAINT employer_master_parent_employer_id_fkey FOREIGN KEY (parent_employer_id) REFERENCES payment_flow.employer_master(id);

ALTER TABLE ONLY payment_flow.employer_payment_receipts
    ADD CONSTRAINT employer_payment_receipts_employer_receipt_number UNIQUE (employer_receipt_number);

ALTER TABLE ONLY payment_flow.employer_payment_receipts
    ADD CONSTRAINT employer_payment_receipts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.employer_toli_relation
    ADD CONSTRAINT employer_toli_relation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.employer_toli_relation
    ADD CONSTRAINT employer_toli_relation_uk_employer_toli UNIQUE (employer_id, toli_id);


ALTER TABLE ONLY payment_flow.worker_toli_relation
    ADD CONSTRAINT worker_toli_relation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.toli_master
    ADD CONSTRAINT toli_master_pkey PRIMARY KEY (id);

ALTER TABLE payment_flow.worker_toli_relation
    ADD CONSTRAINT unique_wrkr_emp_brd_toli
    UNIQUE (worker_id, employer_id, board_id, toli_id);

ALTER TABLE ONLY payment_flow.toli_master
    ADD CONSTRAINT toli_master_registration_number UNIQUE (registration_number);

ALTER TABLE ONLY payment_flow.uploaded_files
    ADD CONSTRAINT uploaded_files_file_reference_number UNIQUE (file_reference_number);

ALTER TABLE ONLY payment_flow.uploaded_files
    ADD CONSTRAINT uploaded_files_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.worker_master
    ADD CONSTRAINT worker_master_aadhar_number UNIQUE (aadhar_number);

ALTER TABLE ONLY payment_flow.worker_master
    ADD CONSTRAINT worker_master_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.worker_master
    ADD CONSTRAINT worker_master_registration_number UNIQUE (registration_number);

ALTER TABLE ONLY payment_flow.worker_payment_receipts
    ADD CONSTRAINT worker_payment_receipts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.worker_payment_receipts
    ADD CONSTRAINT worker_payment_receipts_receipt_number UNIQUE (receipt_number);

ALTER TABLE ONLY payment_flow.worker_payments
    ADD CONSTRAINT worker_payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payment_flow.worker_uploaded_data
    ADD CONSTRAINT worker_uploaded_data_pkey PRIMARY KEY (id);

CREATE INDEX idx_board_receipts_board_employer ON payment_flow.board_receipts USING btree (board_id, employer_id);
CREATE INDEX idx_board_receipts_board_employer_toli ON payment_flow.board_receipts USING btree (board_id, employer_id, toli_id);

ALTER TABLE ONLY payment_flow.board_receipts
    ADD CONSTRAINT board_receipts_toli_id_fkey FOREIGN KEY (toli_id) REFERENCES payment_flow.toli_master(id);

CREATE INDEX idx_employer_payment_board_employer ON payment_flow.employer_payment_receipts USING btree (board_id, employer_id);

CREATE INDEX idx_employer_toli_board_employer ON payment_flow.employer_toli_relation USING btree (board_id, employer_id);

CREATE INDEX idx_uploaded_files_board_employer ON payment_flow.uploaded_files USING btree (board_id, employer_id);

CREATE INDEX idx_worker_payment_receipts_board_employer ON payment_flow.worker_payment_receipts USING btree (board_id, employer_id);

CREATE INDEX idx_worker_payments_board_employer ON payment_flow.worker_payments USING btree (board_id, employer_id);

CREATE INDEX idx_worker_uploaded_data_board_employer ON payment_flow.worker_uploaded_data USING btree (board_id, employer_id);

ALTER TABLE ONLY payment_flow.worker_toli_relation
    ADD CONSTRAINT worker_toli_relation_toli_id_fkey FOREIGN KEY (toli_id) REFERENCES payment_flow.toli_master(id);

ALTER TABLE ONLY payment_flow.worker_toli_relation
    ADD CONSTRAINT worker_toli_relation_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES payment_flow.worker_master(id);


-- Apply standard RLS policies using utility from auth schema
SELECT auth.apply_std_rls_policy('payment_flow', 'board_master', true, true, 'board_id', NULL, NULL);
SELECT auth.apply_std_rls_policy('payment_flow', 'board_receipts', true, true, 'board_id', 'employer_id', 'toli_id');
SELECT auth.apply_std_rls_policy('payment_flow', 'employer_payment_receipts', true, true, 'board_id', 'employer_id', 'toli_id');
SELECT auth.apply_std_rls_policy('payment_flow', 'employer_toli_relation', true, true, 'board_id', 'employer_id', 'toli_id');
SELECT auth.apply_std_rls_policy('payment_flow', 'uploaded_files', true, true, 'board_id', 'employer_id', 'toli_id');
SELECT auth.apply_std_rls_policy('payment_flow', 'worker_payment_receipts', true, true, 'board_id', 'employer_id', 'toli_id');
SELECT auth.apply_std_rls_policy('payment_flow', 'worker_payments', true, true, 'board_id', 'employer_id', 'toli_id');
SELECT auth.apply_std_rls_policy('payment_flow', 'worker_uploaded_data', true, true, 'board_id', 'employer_id', 'toli_id');
SELECT auth.apply_std_rls_policy('payment_flow', 'worker_toli_relation', true, true, 'board_id', 'employer_id', 'toli_id');


-- Create application user for payment_flow service (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'app_payment_flow') THEN
        CREATE ROLE app_payment_flow LOGIN PASSWORD 'changeme';
    END IF;
END$$;

-- Grant privileges to app_payment_flow
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.board_master TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.employer_toli_relation TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.board_receipts TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.employer_payment_receipts TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.uploaded_files TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.worker_payment_receipts TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.worker_payments TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.worker_uploaded_data TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.worker_toli_relation TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.toli_master TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.employer_master TO app_payment_flow;
GRANT INSERT, SELECT, UPDATE, DELETE ON payment_flow.worker_master TO app_payment_flow;

-- Cross-schema grants
GRANT INSERT, SELECT ON audit.audit_event TO app_payment_flow;
GRANT INSERT, SELECT ON audit.entity_audit_event TO app_payment_flow;
GRANT SELECT ON audit.v_recent_events TO app_payment_flow;
GRANT SELECT ON audit.v_entity_changes_today TO app_payment_flow;
GRANT SELECT ON audit.v_activity_summary TO app_payment_flow;
GRANT SELECT ON auth.user_tenant_acl TO app_payment_flow;

-- Grant schema usage
GRANT USAGE ON SCHEMA payment_flow TO app_payment_flow;
-- GRANT USAGE ON SCHEMA audit TO app_payment_flow;

-- Grant all table privileges in schema
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA payment_flow TO app_payment_flow;

