#!/bin/bash

USER="root"
HOST="localhost"
PORT="5432"
SRC_DB="labormanagement"
OUTFILE="lbe_data_inserts.sql"

# List of tables (schema.table)
TABLES=(
"audit.audit_event"
"audit.entity_audit_event"
"audit.flyway_schema_history_audit"
"auth.authorization_audit"
"auth.endpoint_policies"
"auth.endpoints"
"auth.entity_audit_event"
"auth.flyway_schema_history_auth"
"auth.notification_templates"
"auth.page_actions"
"auth.policies"
"auth.revoked_tokens"
"auth.role_policies"
"auth.roles"
"auth.system_config"
"auth.ui_pages"
"auth.user_roles"
"auth.user_sessions"
"auth.user_tenant_acl"
"auth.user_tenant_acl_audit"
"auth.users"
"payment_flow.board_master"
"payment_flow.board_receipts"
"payment_flow.employer_master"
"payment_flow.employer_payment_receipts"
"payment_flow.employer_toli_relation"
"payment_flow.entity_audit_event"
"payment_flow.flyway_schema_history_payment_flow"
"payment_flow.toli_details"
"payment_flow.toli_master"
"payment_flow.uploaded_files"
"payment_flow.worker_master"
"payment_flow.worker_payment_receipts"
"payment_flow.worker_payments"
"payment_flow.worker_uploaded_data"
"reconciliation.bank_account"
"reconciliation.entity_audit_event"
"reconciliation.file_processing_queue"
"reconciliation.flyway_schema_history_reconciliation"
"reconciliation.import_error"
"reconciliation.import_run"
"reconciliation.raw_statement_line"
"reconciliation.statement_balance"
"reconciliation.statement_file"
"reconciliation.statement_transaction"
"reconciliation.transaction_86_segment"
"reconciliation.uploaded_files"
"reconciliation.van_file"
"reconciliation.van_transaction"
)

echo "" > "$OUTFILE"
for table in "${TABLES[@]}"; do
  echo "Exporting $table..."
  pg_dump -U "$USER" -h "$HOST" -p "$PORT" -d "$SRC_DB" --data-only --column-inserts --no-owner --no-privileges -t "$table" >> "$OUTFILE"
done

echo "All data exported to $OUTFILE"