-- Flyway migration: Initial schema for audit
-- Extracted from schema.sql (excluding backup and *_DDMMYY/_YYMMDD objects and audit_* tables outside the audit schema).

CREATE SCHEMA audit;

COMMENT ON SCHEMA audit IS 'Centralized audit logging for all services';

CREATE TABLE audit.audit_event (
    id bigint NOT NULL,
    trace_id character varying(64) NOT NULL,
    action character varying(128) NOT NULL,
    resource_type character varying(64) NOT NULL,
    resource_id character varying(128),
    service_name character varying(50) DEFAULT 'unknown'::character varying NOT NULL,
    source_schema character varying(50) NOT NULL,
    user_id character varying(128) NOT NULL,
    client_ip character varying(64),
    user_agent character varying(256),
    referer character varying(256),
    client_source character varying(64),
    requested_with character varying(64),
    outcome character varying(16) NOT NULL,
    details jsonb,
    prev_hash character varying(64) NOT NULL,
    hash character varying(64) NOT NULL,
    response_hash character varying(64),
    occurred_at timestamp without time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE audit.audit_event IS 'System-level audit events from all services';

COMMENT ON COLUMN audit.audit_event.trace_id IS 'Distributed tracing ID for correlating events';

COMMENT ON COLUMN audit.audit_event.service_name IS 'Source service: auth-service, payment-service, worker-service';

COMMENT ON COLUMN audit.audit_event.source_schema IS 'Database schema where event originated';

ALTER TABLE audit.audit_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME audit.audit_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE audit.entity_audit_event (
    id bigint NOT NULL,
    audit_number character varying(64) NOT NULL,
    record_number character varying(128) NOT NULL,
    entity_type character varying(128) NOT NULL,
    entity_id character varying(128),
    operation character varying(64) NOT NULL,
    service_name character varying(50) DEFAULT 'unknown'::character varying NOT NULL,
    source_schema character varying(50) NOT NULL,
    source_table character varying(100),
    performed_by character varying(128),
    client_ip character varying(45),
    user_agent character varying(512),
    old_values jsonb,
    new_values jsonb,
    change_summary text,
    metadata jsonb,
    trace_id character varying(64),
    prev_hash character(64) NOT NULL,
    hash character(64) NOT NULL,
    occurred_at timestamp without time zone DEFAULT now() NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON TABLE audit.entity_audit_event IS 'Entity-level change tracking from all services';

COMMENT ON COLUMN audit.entity_audit_event.service_name IS 'Source service: auth-service, payment-service, worker-service';

COMMENT ON COLUMN audit.entity_audit_event.source_schema IS 'Database schema where entity resides';

COMMENT ON COLUMN audit.entity_audit_event.source_table IS 'Table name of the audited entity';

ALTER TABLE audit.entity_audit_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME audit.entity_audit_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE VIEW audit.v_activity_summary AS
 SELECT date(occurred_at) AS date,
    service_name,
    source_schema,
    count(*) AS event_count,
    count(DISTINCT user_id) AS unique_users,
    count(DISTINCT trace_id) AS unique_traces
   FROM audit.audit_event
  WHERE (occurred_at > (now() - '30 days'::interval))
  GROUP BY (date(occurred_at)), service_name, source_schema
  ORDER BY (date(occurred_at)) DESC, service_name, source_schema;

COMMENT ON VIEW audit.v_activity_summary IS 'Daily activity summary for last 30 days';

CREATE VIEW audit.v_entity_changes_today AS
 SELECT id,
    occurred_at,
    service_name,
    source_schema,
    source_table,
    entity_type,
    entity_id,
    operation,
    performed_by,
    trace_id
   FROM audit.entity_audit_event
  WHERE (occurred_at >= CURRENT_DATE)
  ORDER BY occurred_at DESC;

COMMENT ON VIEW audit.v_entity_changes_today IS 'All entity changes since midnight';

CREATE VIEW audit.v_recent_events AS
 SELECT id,
    occurred_at,
    service_name,
    source_schema,
    action,
    resource_type,
    resource_id,
    user_id,
    outcome,
    trace_id
   FROM audit.audit_event
  WHERE (occurred_at > (now() - '24:00:00'::interval))
  ORDER BY occurred_at DESC
 LIMIT 1000;

COMMENT ON VIEW audit.v_recent_events IS 'Last 24 hours of audit events (max 1000)';

ALTER TABLE ONLY audit.audit_event
    ADD CONSTRAINT audit_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY audit.entity_audit_event
    ADD CONSTRAINT entity_audit_event_audit_number_key UNIQUE (audit_number);

ALTER TABLE ONLY audit.entity_audit_event
    ADD CONSTRAINT entity_audit_event_pkey PRIMARY KEY (id);

CREATE INDEX idx_audit_event_action ON audit.audit_event USING btree (action);

CREATE INDEX idx_audit_event_occurred_at ON audit.audit_event USING btree (occurred_at DESC);

CREATE INDEX idx_audit_event_outcome ON audit.audit_event USING btree (outcome);

CREATE INDEX idx_audit_event_resource ON audit.audit_event USING btree (resource_type, resource_id);

CREATE INDEX idx_audit_event_service ON audit.audit_event USING btree (service_name);

CREATE INDEX idx_audit_event_source_schema ON audit.audit_event USING btree (source_schema);

CREATE INDEX idx_audit_event_trace_id ON audit.audit_event USING btree (trace_id);

CREATE INDEX idx_audit_event_user_id ON audit.audit_event USING btree (user_id);

CREATE INDEX idx_entity_audit_entity ON audit.entity_audit_event USING btree (entity_type, entity_id);

CREATE INDEX idx_entity_audit_occurred_at ON audit.entity_audit_event USING btree (occurred_at DESC);

CREATE INDEX idx_entity_audit_operation ON audit.entity_audit_event USING btree (operation);

CREATE INDEX idx_entity_audit_performed_by ON audit.entity_audit_event USING btree (performed_by);

CREATE INDEX idx_entity_audit_record_number ON audit.entity_audit_event USING btree (record_number);

CREATE INDEX idx_entity_audit_service ON audit.entity_audit_event USING btree (service_name);

CREATE INDEX idx_entity_audit_source_schema ON audit.entity_audit_event USING btree (source_schema);

CREATE INDEX idx_entity_audit_source_table ON audit.entity_audit_event USING btree (source_table);

CREATE INDEX idx_entity_audit_trace_id ON audit.entity_audit_event USING btree (trace_id);
